version: "3.7"

services:
  mercure:
    image: dunglas/mercure
    container_name: mercure.local
    environment:
      DEMO: 1
      ALLOW_ANONYMOUS: 1
      PUBLISH_ALLOWED_ORIGINS: http://localhost,http://localhost:8080
      CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:8080
      JWT_KEY: this-is-my-pipi
    ports:
      - 80:80
  nginx:
    image: nginx
    container_name: nginx.mercure.local
    volumes:
    - ./public:/usr/share/nginx/html
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=nginx.mercure.local
    - NGINX_PORT=80